spring:
  datasource:
    url: jdbc:mysql://81.4.106.140:3306/abidmehboob_tourism?useLegacyDatetimeCode=false
    username: abidmehboob_app
    password: xFHeneCOoX
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
#      ddl-auto: update
      able_lazy_load_no_trans: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.jdbc.batch_size: 1000 
      jdbc:
        time_zone: UTC
      event:
        merge:
          entity_copy_observer: allow
#    properties:
#       hibernate.jdbc.batch_size: 1000 
#      hibernate:
#        enable_lazy_load_no_trans: true
#        ddl-auto: update
#        jdbc:
#        time_zone: UTC
#      event:
#        merge:
#          entity_copy_observer: allow
#        event:
#          merge:
#            entity_copy_observer: allow
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 20
  main:
    allow-bean-definition-overriding: true
  mail:
    default-encoding: UTF-8
    host: localhost
    username: test
    password: test
    port: 25
    properties:
      mail:
        smtp:
          connectiontimeout: 2000
          timeout: 2000
          writetimeout: 2000
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      
  redis:
    host: 3.15.218.126
    port: 6379

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  include:
    - /**
  exclude:
    - /actuator/**
    - /swagger-ui.html/**
  filter.enabled: true
  format.style: http
  strategy: default
  obfuscate:
    parameters:
      - access_token
      - password
      - token

server:
  port: 8085
  session:
    tracking-modes: cookie

http:
  encryption:
    enabled: false
    aes-key: Z8DQJUY/k0iLFKCfl79jIcSZecHgsG22TgeWo99

jwt:
  employee:
    clientId: employee
    clientSecret: secret
    accessTokenValiditySeconds: 604800
    refreshTokenValiditySeconds: 604800
  customer:
    clientId: customer
    clientSecret: secret
    accessTokenValiditySeconds: 604800
    refreshTokenValiditySeconds: 604800
  security:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme
feign:
  client:
    config:
      AttachmentUploadFeignClient:
        connectTimeout: 50000
        readTimeout: 20000
app:
  firebase-configuration-file: fcm/planckly-2a17b-firebase-adminsdk-0wkbo-2b71d75e7d.json
  firebase-database-url: https://planckly-2a17b.firebaseio.com
  ios-certificate-path: classpath:apns/Certificates.p12
  ios-password: admin123
  
attachment:
  ip: 168.235.86.155
  user-name: root
  password: VnlJQlq1V0
  access-url: http://168.235.86.155/ 
  feign-url: http://168.235.86.155:8085
  directory:
    hotel-images: public_html/file_uploads/hotel_images
    sight-seeing-images: public_html/file_uploads/sight_seeing_images
    deal-images: public_html/file_uploads/deal_images
    

loggin:
  level:
    com:
      planckly:
        shopping:
          feature: FULL
